
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <p><em>&quot;If a house could hug, it would be La Sperduta&quot;</em> - Chris R.</p>
            </div>
        </div>
    </div>
</footer>

<script src="assets/js/jquery-1.10.2.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script>
    $('.carousel').carousel({
        interval: 5000
    })
</script>
</body>
</html>
