<div class="brand">La Sperduta</div>

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">La Sperduta</a>
        </div>

        <ul class="nav navbar-nav">
            <li><a href="index.html">Home</a></li>
            <li><a href="photos.html">Photos</a></li>
        </ul>
    </div>
</nav>
