name: CI

on:
  push:
    branches: [ master ]

jobs:
  build and deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run buildwebsite
      run: |
        npm i
        node buildwebsite.js
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete 
      env: 
        AWS_S3_BUCKET: lasperduta.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist'      # optional: defaults to entire repository
      
      
